# see: https://terraform-docs.io/user-guide/configuration/
# for documentation on how to use this file.
formatter: markdown

header-from: main.tf
#footer-from:

sections:
  hide: []
  show:
    - all
  
content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}
  
  {{ .Modules }}
  
  {{ .Resources }}

  {{ .Outputs }}

output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  #from: 

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
