---
on: [push, pull_request]

name: Commit lint and release
jobs:
  lint_release:
    uses: nrkno/github-workflow-semantic-release/.github/workflows/workflow.yaml@v5.0.3
    with:
      runs-on: ubuntu-latest
