name: Test

on:
  push:
    branches:
  pull_request:
    branches:
      - main

jobs:
  # Runs both Terraform checks and Trivy scan against a valid configuration.
  terraform-valid:
    uses: ./.github/workflows/workflow.yaml
    with:
      working-directory: ./test/terraform
      runs-on: ubuntu-latest
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_KEY_GITHUB_ACTIONS }}

  # Runs Trivy scan against a vulnerable config.
  trivy-invalid:
    uses: ./.github/workflows/workflow.yaml
    with:
      terraform-job-enabled: false
      trivy-error-is-success: true
      working-directory: ./test/trivy
      runs-on: ubuntu-latest
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_KEY_GITHUB_ACTIONS }}
