name: Test

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  # Runs both Terraform checks and Trivy scan against a valid configuration.
  terraform-valid:
    uses: ./.github/workflows/workflow.yaml
    with:
      working-directory: ./test/terraform
      runs-on: ubuntu-latest
      terraform-docs-fail-on-diff: false
      workflow-ref: "${{ github.sha }}"

  # Runs Trivy scan against a vulnerable config.
  trivy-invalid:
    uses: ./.github/workflows/workflow.yaml
    with:
      terraform-job-enabled: false
      trivy-error-is-success: true
      working-directory: ./test/trivy
      runs-on: ubuntu-latest
      workflow-ref: "${{ github.sha }}"
