on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  terraform-config:
    uses: ./.github/workflows/workflow.yaml
    with:
      working-directory: ./test
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_KEY_GITHUB_ACTIONS }}
