on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-config:
    uses: ./.github/workflows/workflow.yaml
    with:
      working-directory: ./test/terraform
      runs-on: ubuntu-latest
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_KEY_GITHUB_ACTIONS }}

  trivy-iac-scan:
    uses: ./.github/workflows/workflow.yaml
    with:
      terraform-job-enabled: false
      trivy-error-is-success: true
      working-directory: ./test/trivy
      runs-on: ubuntu-latest
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      ssh-private-key: ${{ secrets.SSH_KEY_GITHUB_ACTIONS }}
